namespace LlamaCpp.Net.Models;

/// <summary>
///     Enumerates the types of output models that can be generated by the LlamaCpp quantizer.
/// </summary>
public enum ModelType
{
    /// <summary>
    ///     Quantizes all tensors to 32-bit floating-point format.
    /// </summary>
    AllF32 = 0,

    /// <summary>
    ///     Quantizes all tensors to 16-bit floating-point format, except for 1d tensors.
    /// </summary>
    MostlyF16 = 1,

    /// <summary>
    ///     Quantizes all tensors to 4-bit integer format, except for 1d tensors.
    /// </summary>
    MostlyQ40 = 2,

    /// <summary>
    ///     Quantizes all tensors to 4-bit integer format, except for 1d tensors.
    /// </summary>
    MostlyQ41 = 3,

    /// <summary>
    ///     Quantizes all tensors to 4-bit integer format, except for 1d tensors. tok_embeddings.weight and output.weight are
    ///     16-bit floating-point format.
    /// </summary>
    MostlyQ41SomeF16 = 4,

    /// <summary>
    ///     Quantizes all tensors to 8-bit integer format, except for 1d tensors.
    /// </summary>
    MostlyQ80 = 7,

    /// <summary>
    ///     Quantizes all tensors to 5-bit integer format, except for 1d tensors.
    /// </summary>
    MostlyQ50 = 8,

    /// <summary>
    ///     Quantizes all tensors to 5-bit integer format, except for 1d tensors.
    /// </summary>
    MostlyQ51 = 9
}