name: CI Build

on:
#  push:
#    branches: [main, develop]

#  pull_request:

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        dotnet-version: [ '6.0' ]
    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup dotnet
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Setup cuda
      # - uses: Jimver/cuda-toolkit@v0.2.10
      #   id: cuda-toolkit
      #   with:
      #     cuda: '12.1.0'
      # - name: Display cuda version
      #   run: nvcc -V

      # Caching these should make the build significantly quicker
      - name: Cache External Libraries
        uses: actions/cache@v3
        id: extlibs
        with:
          path: |
            .\lib\ClBlast
            .\lib\llama.cpp
            .\lib\OpenBlas
            .\lib\OpenCl
      # Caching these should make the build significantly quicker
      - name: Cache External Libraries
        uses: actions/cache@v3
        id: extlibstmp
        with:
          path: |
            .\tmp\ClBlast
            .\tmp\llama.cpp
            .\tmp\OpenBlas
            .\tmp\OpenCl

      # Cake Build dependencies
      - name: Cake Build dependencies
        run: .\build.ps1 -t Default

      # Cake build nuget package
      - name: Build nuget
        run: .\build.ps1 -t Dotnet.Build
